#!/usr/bin/env bash
##########################################################
#                                                        #
#                SIMPLE WEB MANAGER                      #
#                                                        #
#                BY: Marin Alcaraz                       #
#                 V:1.1  LU:13/02/13                     #
#                                                        #
#   Simple web manager provides an easy way to           #
#   manage apache2 virtual hosts, manage users           #
#   and databases on Ubuntu.                             #
#   Apache virtual host must be enabled.                 #
#                                                        #
#    The content of this file is licensed under          #
#    the MIT license.                                    #
#                                                        #
##########################################################


#General Info

VERSION="Version 1.1"
INFO="Simple Web Manager $VERSION "
BASE_PATH="/home"
VHOST_PATH="/etc/apache2/sites-available"
MYSQL=`which mysql`

echo "$INFO"

#Group validation
/bin/egrep  -i "^web" /etc/group
if [ $? -eq 0 ];
then
    echo "Group verified..."
else
    echo "group web does not exists in /etc/passwd you MUST create it"
    exit
fi

#Menu
echo "Please Select an option"

options=("Add Account" "Delete Account" "Create Database" "Create Database_User" "Manage DB_user permissons" "Quit")
select opt in "${options[@]}"

do
        case $opt in
            "Add Account")
                #Request account name and creates it

                read -p "Give an account: " ACCOUNT
                adduser $ACCOUNT
                    mkdir -p $BASE_PATH/$ACCOUNT/{public_html,private,logs,cgi-bin,backup}
                    chmod -R 755 $BASE_PATH/$ACCOUNT
                    chown -R $ACCOUNT $BASE_PATH/$ACCOUNT
                    chgrp -R web $BASE_PATH/$ACCOUNT
                    read -p "Give a domain: " DOMAIN

                    VHOST_DEFINITION="
                                <VirtualHost *:80>
                                    \n ServerAdmin admin@site.com
                                    \n DocumentRoot /home/$ACCOUNT/public_html
                                    \n ServerName $DOMAIN
                                    \n ServerAlias www.$DOMAIN
                                    \n ErrorLog /home/$ACCOUNT/logs/$DOMAIN-error_log
                               \n </VirtualHost>"
                    touch $VHOST_PATH/$DOMAIN
                    echo -e $VHOST_DEFINITION >> $VHOST_PATH/$DOMAIN
                    a2ensite $DOMAIN
                    service apache2 restart
                    echo -e "ACCOUNT $ACCOUNT SUCCESFULLY CREATED \n"
                ;;

            "Delete Account")
                read -p "Give an account: " ACCOUNT
                read -p "Are you sure?? (1,0) You are attempting to delete  $BASE_PATH/$ACCOUNT/  and all it's content" CONF
                if [ $CONF -eq 1 ]
                then
                    userdel $ACCOUNT
                    rm -rf $BASE_PATH/$ACCOUNT/
                    rm -rf $VHOST_PATH/$ACCOUNT/
                    echo "Account Succesfully Deleted"
                    a2dissite $DOMAIN
                    service apache2 restart
                else
                    echo "There was an errorer deleting the account: $ACCOUNT"
                fi
                ;;

             "Create Database")
                read -p "Database name: " DBNAME
                echo "Create Database"
                    QUERY1="CREATE DATABASE IF NOT EXISTS $DBNAME"
                    $MYSQL -u root -p -e "$QUERY1"
                ;;

            "Create Database_User")
                echo "Create Database_User"
                read -p "Database user name: " DBUSER
                    QUERY2="CREATE USER $DBUSER"
                    $MYSQL -u root -p -e "$QUERY2"
                ;;

            "Manage DB_user permissons")
                echo "Manage DB_user permissons"
                read -p "User name: " DBUSER
                read -p "Set mysql pass: " MSPASS
                read -p "Database: " MSDB

                QUERY3="GRANT ALL ON $MSDB.* TO '$DBUSER'@'localhost' IDENTIFIED BY '$MSPASS'; FLUSH PRIVILEGES;"
                $MYSQL -u root -p -e "$QUERY3"
                ;;

            "Quit")
                break
                ;;
            *) echo "invalid option";;
        esac
done
